### ISSUE TITLE
eslint can't resolve alias paths

### ISSUE THREAD

**Issue by sslotsky** [tleunen/eslint-import-resolver-babel-module#25]
I believe I've followed instructions correctly. I have this package as well as `babel-plugin-module-resolver` installed. My .bablrc:

```javascript
{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": [
    ["module-resolver", {
      "root": ["./"],
      "alias": {
        "ROOT": "./",
        "APP": "./app",
        "CONFIG": "./config",
        "LIB": "./lib"
      }
    }]
  ]
}
```

The app runs fine so the aliases are working, but I get lots of these warnings when linting:

```
Unable to resolve path to module 'APP/shared/forms'
```

I've tried with an .eslintrc like this:

```javasript
{
  "extends": "airbnb",
  "parser": "babel-eslint",
  "plugins": ["react"],
  "settings": {
    "import/resolver": {
      "babel-module": {}
    }
  },
  "rules": {
    "new-cap": [2, { "capIsNewExceptions": ["List", "Map"] }],
    "semi": [2, "never"],
    "comma-dangle": [2, "never"],
    "no-constant-condition": ["off"],
    "import/no-extraneous-dependencies": ["off"]
  }
}
```

and with an .eslintrc.yml like this

```
extends: airbnb
parser: 'babel-eslint'
plugins:
  - react
import/resolver: 'babel-module'
rules:
  new-cap:
    - 2
    - capIsNewExceptions:
      - List
      - Map
  semi:
    - 2
    - never
  comma-dangle:
    - 2
    - never
  no-constant-condition:
    - off
  import/no-extraneous-dependencies:
    - off
```

Makes no difference. Surely I've missed something?
