### ISSUE TITLE
not resolving node_modules, aliases or relative imports in vscode

### ISSUE THREAD

**Issue by davemcorwin** [tleunen/eslint-import-resolver-babel-module#61]
<img width="724" alt="screen shot 2017-06-02 at 9 08 02 am" src="https://cloud.githubusercontent.com/assets/6662371/26729358/080ea208-4773-11e7-9f53-09a6724b1875.png">
<img width="724" alt="screen shot 2017-06-02 at 9 07 43 am" src="https://cloud.githubusercontent.com/assets/6662371/26729359/0818f082-4773-11e7-94e7-dbfea750e21e.png">

.babelrc
```
{
  "plugins": [
    [
      "module-resolver",
      {
        "root": [
          "."
        ],
        "alias": {
          "styles": "./styles",
          "components": "./components",
          "lib": "./lib",
          "pages": "./pages",
          "gql": "./gql"
        },
        "cwd": "babelrc"
      }
    ],
...
}
```
.eslintrc.yml
```
---
  env:
    browser: true
    node: true
    es6: true
  parser: babel-eslint
  parserOptions:
    sourceType: module
    ecmaFeatures:
      experimentalObjectRestSpread: true
      jsx: true
      impliedStrict: true
  plugins:
    - react
  extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:import/errors
    - plugin:import/warnings    
  settings:
    import/resolver: babel-module
```

any thoughts? something I am doing wrong?

**Comment by tleunen** [comment]
Could you show me the structure of your project?
If you have a public repo with the issue, I'd love to take a look

**Comment by davemcorwin** [comment]
Thanks for the quick response! Unfortunately, its not a public repo. I'm using [Next.js](https://github.com/zeit/next.js) and sticking with their file structure so far, but its nothing unusual (other than not having a root `src` dir):
- /
  - node_modules
  - components
  - pages
  - gql
  - lib
  - .babelrc
  - .eslintrc.yml
  - etc...

It seems strange that it can't resolve stuff from node_modules, is there a decent way to debug this so I can be a bit more helpful?

**Comment by davemcorwin** [comment]
Also, it is something within eslint itself not VSCode, i have the same issues in Atom and running on the command line.

**Comment by davemcorwin** [comment]
sorry to spam, here is my entire .babelrc:
```
{
  "plugins": [
    [
      "module-resolver",
      {
        "root": [
          "."
        ],
        "alias": {
          "styles": "./styles",
          "components": "./components",
          "lib": "./lib",
          "pages": "./pages",
          "gql": "./gql"
        },
        "cwd": "babelrc"
      }
    ],
    [
      "wrap-in-js",
      {
        "extensions": [
          "css$",
          "scss$"
        ]
      }
    ],
    [
      "lodash",
      {
        "id": [
          "lodash",
          "recompose"
        ]
      }
    ],
    "babel-plugin-inline-import-graphql-ast",
    "inline-dotenv"
  ],
  "presets": [
    "next/babel"
  ],
  "env": {
    "test": {
      "presets": [
        {
          "modules": "commonjs"
        }
      ]
    }
  },
  "ignore": []
}
```

The `next/babel` preset can be found [here](https://github.com/zeit/next.js/blob/v3-beta/server/build/babel/preset.js)

**Comment by tleunen** [comment]
I bet this is some strange edge cases with the custom root being `"."`.

Could you try removing it, but keeping your alias for the directories?

**Comment by davemcorwin** [comment]
no change. Wondering if it can find the file, since it displays the module in the popup (see screenshots above), but for some reason it can't resolve the export. Could it be something i'm missing on the babel side ?

**Comment by davemcorwin** [comment]
the aliases work in the actual application so I think that the module-resolver config in .babelrc is ok, its just eslint that can't find it.

**Comment by davemcorwin** [comment]
Hmm, i got it to work for node_modules and relative paths by changing the following in my .eslintrc.yml:

from
```
  settings:
    import/resolver: babel-module
```
to
```
  settings:
    import/resolver:
      babel-module:
        foo: bar
```
